export const iconSource = {
	"01d": "../assets/sun.gif",
	"01n": "../assets/night.gif",
	"02d": "../assets/clouds.gif",
	"02n": "../assets/clouds.gif",
	"03d": "../assets/weather.gif",
	"03n": "../assets/weather.gif",
	"04d": "../assets/weather.gif",
	"04n": "../assets/weather.gif",
	"09d": "../assets/rain.gif",
	"09n": "../assets/rain.gif",
	"10d": "../assets/rainy.gif",
	"10n": "../assets/nightRainy.gif",
	"11d": "../assets/storm.gif",
	"11n": "../assets/storm.gif",
	"13d": "../assets/snow.gif",
	"13n": "../assets/snow.gif",
	"50d": "../assets/foggy.gif",
	"50n": "../assets/foggy.gif",
};
